---
#-------------------------------------------------------------------
# authors     [ Radhouene AZZABI ]
# contacts    [ azzabi.radhouene@cea.fr ]
# created     2024/11-20T15:40:24
# modified    2024/11-20T15:40:24
# version     1.0.0
#-------------------------------------------------------------------

version: "3"

#dotenv: ['../.env'] # uncomment if you want to test tasks localy

tasks:
  start:
    desc: "Start Web-UI"
    silent: true
    preconditions:
      - test -f {{.TASKFILE_DIR}}/docker-compose.yml
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml up --force-recreate --pull always webui --wait

  stop:
    desc: "Stop Web-UI"
    silent: true
    preconditions:
      - test {{.TASKFILE_DIR}}/docker-compose.yml
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml down webui

  upgrade:
    desc: "Upgrade the Webui"
    silent: true
    preconditions:
      - test -f {{.TASKFILE_DIR}}/docker-compose.yml
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml pull --ignore-pull-failures
