services:
  cde:
    image: ghcr.io/que-technologies/datacellar-cde:latest
    container_name: ${PARTICIPANT_NAME}.cde
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5001:5001"
    environment:
      FLASK_DEBUG: development
      CDE_INFLUXDB_URL: http://influxdb:8086
      CDE_INFLUXDB_TOKEN: ${CDE_INFLUXDB_TOKEN}
      CDE_INFLUXDB_ORG: ${CDE_INFLUXDB_ORG}
      CDE_INFLUXDB_BUCKET: ${CDE_INFLUXDB_BUCKET}
      CDE_FUSEKI_URL: http://fuseki:3030
    depends_on:
      influxdb:
        condition: service_healthy
      fuseki:
        condition: service_healthy
    networks:
      - datacellar

  influxdb:
    image: influxdb:2.6
    container_name: ${PARTICIPANT_NAME}.influxdb
    ports:
      - "127.0.0.1:8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${CDE_INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${CDE_INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${CDE_INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${CDE_INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${CDE_INFLUXDB_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - datacellar

  fuseki:
    image: stain/jena-fuseki
    container_name: ${PARTICIPANT_NAME}.fuseki
    environment:
      ADMIN_PASSWORD: ${CDE_FUSEKI_PASSWORD} 
      JVM_ARGS: -Xmx2g
    ports:
      - "127.0.0.1:3030:3030"
    volumes:
      - fuseki-data:/fuseki
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - datacellar

volumes:
  influxdb-data:
  fuseki-data:

networks:
  datacellar:
    external: true
    name: datacellar_network
