services:
  credentials-api:
    image: docker.io/razzabi/datacellar-cli:v0.4.44
    container_name: ${PARTICIPANT_NAME}.credentials-api
    restart: unless-stopped
    command: datacellar serve-api --port 8080
    volumes:
      - ${CREDENTIALS_FOLDER}:/credentials
      - ${CERT_FOLDER}:/certs
      - ${WALLET_FOLDER}/waltid/data:/waltid
    # ports:
    #   - 8080:8080
    environment:
      CREDENTIALS_MANAGER_API: "http://credentials-api:8080/api/v1"
      DATACELLAR_API_BASE_URL: ${DATACELLAR_API_BASE_URL}
      WALLET_API_BASE_URL: ${WALLET_API_BASE_URL}
      WALLET_USER_NAME: ${WALLET_USER_NAME}
      WALLET_USER_EMAIL: ${WALLET_USER_EMAIL}
      WALLET_USER_PASSWORD: ${WALLET_USER_PASSWORD}
      DID_WEB_DOMAIN: ${DID_WEB_DOMAIN}
      ISSUER_API_KEY: ${ISSUER_API_KEY}

      EDC_CONNECTOR_SCHEME: http
      EDC_CONNECTOR_HOST: "${PARTICIPANT_NAME}.${DOMAIN_NAME}"
      EDC_CONNECTOR_CONNECTOR_ID: "${PARTICIPANT_NAME}"
      EDC_CONNECTOR_PARTICIPANT_ID: "${PARTICIPANT_NAME}"
      EDC_CONNECTOR_MANAGEMENT_PORT: 80
      EDC_CONNECTOR_CONTROL_PORT: 80
      EDC_CONNECTOR_PUBLIC_PORT: 80
      EDC_CONNECTOR_PROTOCOL_PORT: 80
      EDC_CONNECTOR_API_KEY: ${EDC_CONNECTOR_API_KEY}
      EDC_CONNECTOR_API_KEY_HEADER: ${EDC_CONNECTOR_API_KEY_HEADER}

      EDC_RABBIT_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${PARTICIPANT_NAME}.connector-broker:5672
    networks:
      - datacellar

networks:
  datacellar:
    external: true
    name: datacellar_network
