#-------------------------------------------------------------------
# authors     [ Radhouene AZZABI ]
# contacts    [ azzabi.radhouene@cea.fr ]
# created     2024/10-15T12:12:24
# modified    2024/10-15T12:12:24
# version     1.0.0
#-------------------------------------------------------------------

version: "3"


# dotenv: ['../.env'] # uncomment if you want to test tasks localy

tasks:
  start:
    desc: "Start DID Server"
    silent: true
    deps:
      - config
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml up did-server -d --wait
  stop:
    desc: "Stop DID Server"
    silent: true
    cmds:
        - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml down did-server
  
  config:
    desc: "Config DID Server"
    silent: true
    dir: '{{.CREDENTIALS_FOLDER}}'
    cmds:
      - sudo chmod -R 755 vc
      - sudo chmod -R 755 vp
      - sudo chmod -R 755 .well-known

  upgrade:
    desc: "Upgrade the did-server"
    silent: true
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} -f {{.TASKFILE_DIR}}/docker-compose.yml pull --ignore-pull-failures --quiet --policy always
