#-------------------------------------------------------------------
# authors     [ Radhouene AZZABI ]
# contacts    [ azzabi.radhouene@cea.fr ]
# created     2024/10-15T12:12:24
# modified    2024/10-15T12:12:24
# version     1.0.0
#-------------------------------------------------------------------

version: "3"


# dotenv: ['../.env'] # uncomment if you want to test tasks localy

tasks:
  start:
    desc: "Start DID Server"
    deps:
      - config
    dir: '{{.DID_SERVER_FOLDER}}'
    cmds:
      - docker compose -p {{.PARTICIPANT_NAME}} up did-server -d --wait
  stop:
    desc: "Stop DID Server"
    dir: '{{.DID_SERVER_FOLDER}}'
    cmds:
        - docker compose -p {{.PARTICIPANT_NAME}} down did-server
  
  config:
    desc: "Config DID Server"
    dir: '{{.CREDENTIALS_FOLDER}}'
    cmds:
      - sudo chmod -R 755 vc
      - sudo chmod -R 755 vp
      - sudo chmod -R 755 .well-known